apiVersion: v2
appVersion: "10.9.0"
description: Jellyfin Media Server
name: jellyfin
version: 10.9.1
type: application
home: https://jellyfin.org/
icon: https://jellyfin.org/images/logo.svg
kubeVersion: >= 1.26.0 < 1.31.0
keywords:
  - jellyfin
  - media
  - self-hosted
